Disable NFC cards
svsticky/constipated-koala pull request #805
Opened 2021-03-09 20:10 UTC by CrookedGrandma

Closes #453 

Adds a new table (card) to the member overview, in which the member's cards can be seen. 
For each card, the UUID is shown and its status next to that.

From this overview, you can:
- Activate cards that have not been activated yet
- Deactivate cards
- Reactivate deactivated cards

2021-03-17 10:42 UTC, JustNireon requested changes

2021-03-17 10:42 UTC, JustNireon commented on app/controllers/api/checkout_controller.rb
> +    @card = CheckoutCard.find_by(uuid: @uuid)
Should first check if card exists otherwise return 404. @card.active gives an error now since @card is nil in certain scenarios

2021-03-17 10:42 UTC, JustNireon commented on app/assets/javascripts/admin/members.js
> +  function button_action() {
This function also get's called in admin/checkout when activating / removing cards not really sure how but it happens

2021-03-17 10:42 UTC, JustNireon commented on app/controllers/api/checkout_controller.rb
> +    render status: :unauthorized, json: I18n.t('checkout.error.not_activated') unless @card.active
Should check if @card is nil before this now it happens afterwards in 'info' or never

2021-03-30 16:11 UTC, JustNireon requested changes
First have to initiate card to check if it's nil :)

2021-03-30 16:11 UTC, JustNireon commented on app/controllers/api/checkout_controller.rb
> +    render status: :not_found if @card.nil?
```suggestion
    
```

2021-03-30 16:11 UTC, JustNireon commented on app/controllers/api/checkout_controller.rb
> +    render status: :unauthorized, json: I18n.t('checkout.error.not_activated') unless @card.active
```suggestion
    render status: :not_found && return if @card.nil?
    render status: :unauthorized, json: I18n.t('checkout.error.not_activated') unless @card.active
```

2021-03-30 17:08 UTC, CrookedGrandma commented on app/controllers/api/checkout_controller.rb
> +    render status: :not_found if @card.nil?
Lmao literally -69 IQ, fixed

2021-04-06 11:21 UTC, JustNireon approved these changes
LGTM

2021-04-06 11:21 UTC, merged