Feature/minor issues payconiq
svsticky/constipated-koala pull request #865
Opened 2021-08-08 21:05 UTC by JustNireon

resolves #856 
Also reworked the member payment page to make it more accessible.
Example:
![image](https://user-images.githubusercontent.com/12464084/128645634-e825f65b-0f01-415d-9be3-a4bf9fc9e3f5.png)

Should be noted that there is a migration to limit the amount of characters to 52 since this is the limit of Exact descriptions. Shouldn't an issue since no activity should be longer than 52 characters.

2021-08-10 10:12 UTC, Riscky commented on config/locales/en.yml
> +        price: PriceNaam
I don't think this is correct?

2021-08-10 10:13 UTC, Riscky commented on config/locales/members.en.yml
> +        subtitle: You can solely use mongoose credit to pay for product in Sticky's room.
You can **only** use **M**ongoose credit to pay for product**s** in Sticky's room.

2021-08-10 10:14 UTC, Riscky commented on config/locales/members.en.yml
> +        transaction_costs: transaction costs charged
start with capital

2021-08-10 10:15 UTC, Riscky commented on config/locales/members.nl.yml
> +        mongoose-info: Mongoose credit is not to pay for activities or membership. You can solely use mongoose credit to pay for product in Sticky's room.
Dit is de NL file, terugveranderen naar nederlands gerne :)

2021-08-10 10:15 UTC, Riscky commented on config/locales/members.nl.yml
> +        subtitle: Mongoose kan je uitsluitend gebruiken om in de sticky gezelligheidskamer producten te kopen.
**S**ticky

2021-08-10 10:17 UTC, Riscky commented on db/migrate/20210808184948_limit_activity_characters.rb
> +    Activity.where('length(name) > 52').each {|activity|
geen down migratie, terwijl dat wel vrij makkelijk is (limit terugveranderen, activiteitnamen gelijkhouden)

2021-08-10 10:25 UTC, Riscky commented on app/views/members/payments/index.html.haml
> +            %i.fa.fa-fw.fa-fw.fa-shopping-cart
dubbele `fa-fw`

2021-08-10 10:27 UTC, Riscky requested changes
Really happy with this PR :)
Lots of small comments, so please go through your code thoroughly.

2021-08-12 16:03 UTC, Mstiekema requested changes
Looking good, please look at the two relevant comments and fix if needed :)

2021-08-12 16:03 UTC, Mstiekema commented on config/locales/members.nl.yml
> +        transaction_costs: transaction costs charged
Reden dat dit van Nederlands naar Engels is veranderd?

2021-08-12 16:03 UTC, Mstiekema commented on db/seeds/payments.rb
> +  15.times do
'vo

2021-08-12 16:54 UTC, Mstiekema approved these changes
Lgtm :)

2021-08-12 17:03 UTC, merged